/* automatically generated by rust-bindgen 0.71.1 */

#[allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod root {
    #[allow(unused_imports)]
    use self::super::root;
    pub const POSIX: u32 = 1;
    pub const LINUX: u32 = 1;
    pub const _LINUX: u32 = 1;
    pub const COMPILER_GCC: u32 = 1;
    pub const MMS_BUILD_TAG: &[u8; 7] = b"manual\0";
    pub const MMS_BUILD_LOCAL_REV: &[u8; 2] = b"0\0";
    pub const MMS_BUILD_CSET: &[u8; 2] = b"0\0";
    pub const MMS_BUILD_MAJOR: &[u8; 2] = b"2\0";
    pub const MMS_BUILD_MINOR: &[u8; 2] = b"0\0";
    pub const MMS_BUILD_RELEASE: &[u8; 2] = b"0\0";
    pub const MMS_BUILD_UNIQUEID: &[u8; 4] = b"0:0\0";
    pub const MMS_VERSION_STRING: &[u8; 13] = b"2.0.0-manual\0";
    pub const METAMOD_VERSION: &[u8; 13] = b"2.0.0-manual\0";
    pub const METAMOD_BUILD_ID: &[u8; 4] = b"0:0\0";
}
